version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: battletech-editor-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api
      # SQLite database file path (embedded in the container)
      DATABASE_URL: sqlite:///usr/src/app/battletech_dev.sqlite
      DB_TYPE: sqlite
      DB_PATH: /usr/src/app/battletech_dev.sqlite
    volumes:
      # Mount a volume for persistent SQLite database storage
      - sqlite_data:/usr/src/app/data
      # Optional: Mount the database file directly for persistence
      - battletech_db:/usr/src/app/battletech_dev.sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/scripts/test-db.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  sqlite_data:
    driver: local
  battletech_db:
    driver: local
