/**
 * Test Equipment Displacement Fix
 * Tests that equipment is properly displaced to unallocated pool when engine changes to XL
 */

import { UnitCriticalManager } from '../../utils/criticalSlots/UnitCriticalManager';
import { EquipmentObject } from '../../utils/criticalSlots/CriticalSlot';

describe('Equipment Displacement Fix', () => {
  function createTestUnit() {
    const config = {
      engineType: 'Standard' as const,
      gyroType: 'Standard' as const,
      mass: 50,
      unitType: 'BattleMech' as const
    };
    
    return new UnitCriticalManager(config);
  }

  function addTestEquipment(unit: UnitCriticalManager) {
    const testEquipment: EquipmentObject[] = [
      {
        id: 'test_weapon_1',
        name: 'AC/10',
        type: 'weapon',
        requiredSlots: 7,
        weight: 12,
        techBase: 'Inner Sphere'
      },
      {
        id: 'test_weapon_2',
        name: 'Medium Laser',
        type: 'weapon',
        requiredSlots: 1,
        weight: 1,
        techBase: 'Inner Sphere'
      }
    ];

    // Add equipment to unallocated pool first, then allocate to available slots
    const allocations = testEquipment.map(equipment => ({
      equipmentData: equipment,
      equipmentGroupId: `${equipment.id}_group`,
      location: '',
      startSlotIndex: -1,
      endSlotIndex: -1,
      occupiedSlots: []
    }));
    
    unit.addUnallocatedEquipment(allocations);
    
    // Try to allocate equipment from pool to available slots
    const equipmentGroups = unit.getUnallocatedEquipment();
    let successfulAllocations = 0;
    
    // Try to place AC/10 in Left Torso - find available contiguous slots
    const leftTorso = unit.getSection('Left Torso');
    if (leftTorso && equipmentGroups.length > 0) {
      // Find first available contiguous slots for AC/10 (7 slots needed)
      for (let i = 0; i <= 12 - 7; i++) { // 12 slots total, need 7 contiguous
        if (unit.allocateEquipmentFromPool(equipmentGroups[0].equipmentGroupId, 'Left Torso', i)) {
          successfulAllocations++;
          break;
        }
      }
    }
    
    // Try to place Medium Laser in Right Torso - find available slot
    const remainingEquipment = unit.getUnallocatedEquipment();
    const rightTorso = unit.getSection('Right Torso');
    if (rightTorso && remainingEquipment.length > 0) {
      // Find first available slot for Medium Laser (1 slot needed)
      for (let i = 0; i < 12; i++) { // 12 slots total
        if (unit.allocateEquipmentFromPool(remainingEquipment[0].equipmentGroupId, 'Right Torso', i)) {
          successfulAllocations++;
          break;
        }
      }
    }
    
    console.log(`Successfully allocated ${successfulAllocations} out of ${testEquipment.length} equipment pieces`);
    return testEquipment;
  }

  test('equipment should be displaced to unallocated pool when engine changes to XL', () => {
    // Step 1: Create unit with Standard engine
    const unit = createTestUnit();
    expect(unit.getEngineType()).toBe('Standard');
    
    // Step 2: Add test equipment
    const equipment = addTestEquipment(unit);
    expect(equipment).toHaveLength(2);
    
    // Verify initial state (accounting for system-generated heat sinks)
    const initialSummary = unit.getSummary();
    expect(initialSummary.totalEquipment).toBe(2);
    // Note: unallocatedEquipment may include heat sinks generated by the system
    const baseUnallocatedCount = initialSummary.unallocatedEquipment;
    
    // Step 3: Change engine to XL (this should displace equipment, not remove it)
    const newConfig = {
      ...unit.getConfiguration(),
      engineType: 'XL' as const
    };
    
    unit.updateConfiguration(newConfig);
    
    // Step 4: Verify fix worked
    const afterSummary = unit.getSummary();
    const unallocatedEquipment = unit.getUnallocatedEquipment();

    // Helper to filter user equipment only
    function isUserEquipment(eq: any) {
      const name = eq.equipmentData?.name?.toLowerCase?.() || '';
      const systemPatterns = [
        'engine', 'gyro', 'heat sink', 'jump jet', 'cockpit', 'life support', 'sensors',
        'shoulder', 'upper arm', 'lower arm', 'hand', 'hip', 'upper leg', 'lower leg', 'foot',
        'structure', 'armor'
      ];
      return !systemPatterns.some(pattern => name.includes(pattern));
    }

    // Count only user equipment
    const allocatedUserEquipment = [];
    unit.getAllSections().forEach(section => {
      section.getAllEquipment().forEach(eq => {
        if (isUserEquipment(eq)) allocatedUserEquipment.push(eq);
      });
    });
    const unallocatedUserEquipment = unallocatedEquipment.filter(isUserEquipment);
    const totalUserEquipmentAfter = allocatedUserEquipment.length + unallocatedUserEquipment.length;

    // Verify engine changed
    expect(unit.getEngineType()).toBe('XL');

    // Verify all user equipment is preserved
    expect(totalUserEquipmentAfter).toBe(2);

    // Verify some equipment was displaced (should have more unallocated user equipment than base)
    expect(unallocatedUserEquipment.length).toBeGreaterThanOrEqual(1);
  });

  test('equipment should remain preserved when changing back to Standard engine', () => {
    // Step 1: Create unit and add equipment
    const unit = createTestUnit();
    addTestEquipment(unit);
    
    // Step 2: Change to XL
    const xlConfig = {
      ...unit.getConfiguration(),
      engineType: 'XL' as const
    };
    unit.updateConfiguration(xlConfig);
    
    // Step 3: Change back to Standard
    const standardConfig = {
      ...unit.getConfiguration(),
      engineType: 'Standard' as const
    };
    unit.updateConfiguration(standardConfig);
    
    // Step 4: Verify equipment is still preserved
    const finalSummary = unit.getSummary();
    const totalEquipmentFinal = finalSummary.totalEquipment + finalSummary.unallocatedEquipment;
    expect(totalEquipmentFinal).toBe(2);
    
    // Verify engine is back to Standard
    expect(unit.getEngineType()).toBe('Standard');
  });

  test('specific equipment displacement scenarios', () => {
    const unit = createTestUnit();
    
    // Add equipment to specific slots that will conflict with XL engine
    const conflictEquipment: EquipmentObject[] = [
      {
        id: 'conflict_equipment_1',
        name: 'Conflicting Equipment 1',
        type: 'equipment',
        requiredSlots: 1,
        weight: 1,
        techBase: 'Inner Sphere'
      },
      {
        id: 'conflict_equipment_2',
        name: 'Conflicting Equipment 2',
        type: 'equipment',
        requiredSlots: 1,
        weight: 1,
        techBase: 'Inner Sphere'
      }
    ];

    // Add equipment to unallocated pool first
    const allocations = conflictEquipment.map(equipment => ({
      equipmentData: equipment,
      equipmentGroupId: `${equipment.id}_group`,
      location: '',
      startSlotIndex: -1,
      endSlotIndex: -1,
      occupiedSlots: []
    }));
    
    unit.addUnallocatedEquipment(allocations);
    
    // Allocate equipment to slots that will conflict with XL engine (torso slots)
    const equipmentGroups = unit.getUnallocatedEquipment();
    let successfulAllocations = 0;
    
    // Try to place equipment in Left Torso
    if (equipmentGroups.length > 0) {
      for (let i = 0; i < 12; i++) {
        if (unit.allocateEquipmentFromPool(equipmentGroups[0].equipmentGroupId, 'Left Torso', i)) {
          successfulAllocations++;
          break;
        }
      }
    }
    
    // Try to place equipment in Right Torso
    const remaining = unit.getUnallocatedEquipment();
    if (remaining.length > 0) {
      for (let i = 0; i < 12; i++) {
        if (unit.allocateEquipmentFromPool(remaining[0].equipmentGroupId, 'Right Torso', i)) {
          successfulAllocations++;
          break;
        }
      }
    }
    
    // Verify initial allocation (accounting for system-generated equipment)
    const initialSummary = unit.getSummary();
    expect(initialSummary.totalEquipment).toBe(successfulAllocations);
    
    // Account for system-generated equipment (like heat sinks) in unallocated count
    const systemGeneratedCount = initialSummary.unallocatedEquipment - Math.max(0, conflictEquipment.length - successfulAllocations);
    expect(systemGeneratedCount).toBeGreaterThanOrEqual(0);
    
    // Change to XL engine - this should displace equipment in torso slots
    const newConfig = {
      ...unit.getConfiguration(),
      engineType: 'XL' as const
    };
    unit.updateConfiguration(newConfig);
    
    // Verify equipment displacement behavior
    const afterSummary = unit.getSummary();
    const totalEquipmentAfter = afterSummary.totalEquipment + afterSummary.unallocatedEquipment;
    
    // Equipment should be preserved (either allocated or displaced to unallocated)
    expect(totalEquipmentAfter).toBe(successfulAllocations);
    
    // Some equipment should be displaced due to XL engine taking more slots
    expect(afterSummary.unallocatedEquipment).toBeGreaterThanOrEqual(0);
  });
});
